export const environment = {
  production: true,
  olprrapi: 'http://deqwebdev/olprrapi/olprr/',
  olprrapi_state: 'http://deqwebdev/olprrapi/olprr/state',
  olprrapi_sitetype: 'http://deqwebdev/olprrapi/olprr/sitetype',
  olprrapi_confirmationtype: 'http://deqwebdev/olprrapi/olprr/confirmationtype',
  olprrapi_county: 'http://deqwebdev/olprrapi/olprr/county',
  olprrapi_discoverytype: 'http://deqwebdev/olprrapi/olprr/discoverytype',
  olprrapi_quadrant: 'http://deqwebdev/olprrapi/olprr/quadrant',
  olprrapi_releasecausetype: 'http://deqwebdev/olprrapi/olprr/releasecausetype',
  olprrapi_sourcetype: 'http://deqwebdev/olprrapi/olprr/sourcetype',
  olprrapi_streettype: 'http://deqwebdev/olprrapi/olprr/streettype',
  olprrapi_deqoffice: 'http://deqwebdev/olprrapi/olprr/deqoffice',
  olprrapi_incidentstatus: 'http://deqwebdev/olprrapi/olprr/incidentstatus',
  olprrapi_incident: 'http://deqwebdev/olprrapi/olprr/incident',
  olprrapi_lust_search: 'http://deqwebdev/olprrapi/lust/search',
  olprrapi_review_search: 'http://deqwebdev/olprrapi/review',
  contractor_uid: 'INGRID',
  contractor_pwd: 'GAFFNEY'
};
